### PR TITLE
Chore/update deps

### PR DESCRIPTION
**Pull request by snodnipper**
update to latest stable dependencies.

Regenerated VectorTile.java with protoc

(Tests passed successfully on Android API 16 emulator)

### CODE REVIEW

**Comment by ShibaBandit** [comment]
Changes look good. Have you tried this in your projects by any chance?

**Comment by snodnipper** [comment]
+1 I see you have merged now.  I have used the org.locationtech.jts code just fine.  The minor deps should be fine.  The protobuf code is generated from the committed proto file...so I *hope* all is good.  I'll build our wares against this and raise any issues.
Thanks!

**Comment by ShibaBandit** [comment]
I'm trying out this version locally before I push to central. I'm a bit torn on the JTS change since this could be fairly divisive for people. For example, if you have a project that uses vividsolutions JTS then it makes this library not very compatible. It kind of forces the client to use the latest JTS and change all of their imports which they may not want to do.

**Comment by snodnipper** [comment]
Sure, check out what you think locally.  I don't believe that it should be a problem for folks as practically it is a version bump.

The change in namespace largely around the licensing - where LocationTech members, including the organisation I work for, supported this work such that it can be integrated better with commercial applications.

LGPL is a grey area in Android because it is practically not possible for folks to swap the library (e.g. downloaded from the Google Play Store).  The EPL is a great achievement in this area and a business-friendly free software license.

Perhaps if you are concerned about users having old imports then we publish two versions now - where there is a final com.vividsolutions version and all future versions are org.locationtech, which is the supported version.  The com.vividsolutions import version is not, strictly speaking, suitable for Android applications as it is LGPL.

**Comment by ShibaBandit** [comment]
Yes I agree. I've been following the JTS development for the last several years and am glad to see it finally out under a new license. I think maybe I can just refer people to 2.0.0 if they want the old namespace for now.

**Pull request merged**
